-- ========================================
-- DEPLOY DESCRIPTOR SYSTEM TO PRODUCTION
-- ========================================
-- Run this script in Supabase Studio SQL Editor
-- https://supabase.com/dashboard/project/iolimejvugpcpnmruqww/sql
--
-- This will create all 5 descriptor tables and seed data
-- ========================================

-- PART 1: CREATE DESCRIPTOR TABLES
-- Copy and paste the contents of: supabase/migrations/20251108_create_descriptor_system.sql

-- PART 2: SEED DESCRIPTOR DATA
-- Copy and paste the contents of: supabase/migrations/20251109_seed_descriptors.sql

-- ========================================
-- ALTERNATIVE: Use Supabase CLI from Git Bash
-- ========================================
-- If you have Git Bash installed, try this:
--
-- 1. Open Git Bash (not PowerShell or CMD)
-- 2. Navigate to project: cd /f/Projects/tuckandtaleMVP/tuckandtaleMVP
-- 3. Run: npx supabase db push --linked -p adsdf7897JKH
--
-- Git Bash often has better network handling for these connections
-- ========================================

-- ========================================
-- MANUAL DEPLOYMENT STEPS
-- ========================================
--
-- 1. Go to: https://supabase.com/dashboard/project/iolimejvugpcpnmruqww/sql
--
-- 2. Create a new query and paste the ENTIRE contents of:
--    supabase/migrations/20251108_create_descriptor_system.sql
--
-- 3. Click "Run" to create all tables
--
-- 4. Create another new query and paste the ENTIRE contents of:
--    supabase/migrations/20251109_seed_descriptors.sql
--
-- 5. Click "Run" to seed the data
--
-- 6. Verify by running:
--    SELECT COUNT(*) FROM descriptors_attribute;
--    SELECT COUNT(*) FROM descriptors_age;
--    SELECT COUNT(*) FROM descriptors_gender;
--    SELECT COUNT(*) FROM descriptors_pet;
--    SELECT COUNT(*) FROM descriptors_magical;
--    SELECT COUNT(*) FROM descriptor_mappings;
--
-- Expected counts:
-- - descriptors_attribute: ~60 rows (hair, eyes, skin, body)
-- - descriptors_age: 19 rows (ages 0-18)
-- - descriptors_gender: 6 rows
-- - descriptors_pet: ~30 rows
-- - descriptors_magical: ~30 rows
-- - descriptor_mappings: 6 rows
--
-- ========================================