-- Add narrative text and ordering columns to vignette_panels
-- This enables OpenAI Vision API to provide story text for each panel

-- Add columns to vignette_panels table
ALTER TABLE public.vignette_panels
ADD COLUMN panel_text text,
ADD COLUMN panel_order integer CHECK (panel_order >= 1 AND panel_order <= 8),
ADD COLUMN is_cover boolean DEFAULT false;

-- Add unique constraint on story_id + panel_order (excluding cover)
-- This ensures each story has a logical reading sequence
CREATE UNIQUE INDEX vignette_panels_story_order_idx
ON public.vignette_panels (story_id, panel_order)
WHERE panel_order IS NOT NULL;

-- Add constraint: only one cover per story
CREATE UNIQUE INDEX vignette_panels_one_cover_idx
ON public.vignette_panels (story_id, is_cover)
WHERE is_cover = true;

-- Comment on columns
COMMENT ON COLUMN public.vignette_panels.panel_text IS 'Story narrative text for this panel, generated by OpenAI Vision API';
COMMENT ON COLUMN public.vignette_panels.panel_order IS 'Reading order (1-8) as determined by OpenAI. NULL for cover panel.';
COMMENT ON COLUMN public.vignette_panels.is_cover IS 'True if this panel is designated as the storybook cover (no narrative text)';

-- Display updated schema
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'vignette_panels'
ORDER BY ordinal_position;
